#!/bin/sh
# image-customize script to prepare a bots VM for cockpit-apparmor testing
set -eu

if command -v dnf >/dev/null 2>&1; then
    dnf install -y apparmor-utils
elif command -v apt-get >/dev/null 2>&1; then
    apt-get update
    apt-get install -y apparmor-utils
fi

# don't force https:// (self-signed cert)
mkdir -p /etc/cockpit
printf "[WebService]\\nAllowUnencrypted=true\\n" > /etc/cockpit/cockpit.conf

if systemctl is-active -q firewalld.service; then
    firewall-cmd --add-service=cockpit --permanent
fi